-- Read-only snapshot source used during the opening window.
BEGIN READ ONLY;

 SELECT json_build_object('kind','counts','readAt',clock_timestamp(),'outboxTotal',(SELECT count(*) FROM indexnow_outbox),'attemptTotal',(SELECT count(*) FROM indexnow_outbox_attempt),'sweepTotal',(SELECT count(*) FROM schedule_run WHERE schedule_key='indexnow.sweep'),'pending',(SELECT count(*) FROM indexnow_outbox WHERE status IN ('pending','retry_wait','processing')),'configMissing',(SELECT count(*) FROM indexnow_outbox WHERE last_error_kind='config_missing')+(SELECT count(*) FROM generic_task_item i JOIN generic_task t ON t.id=i.task_id WHERE t.task_type='indexnow_delivery' AND i.result->>'reason'='config_missing'),'forbiddenHttp',(SELECT count(*) FROM indexnow_outbox_attempt WHERE http_status IN (403,422)),'attemptedOutboxes',(SELECT count(DISTINCT outbox_id) FROM indexnow_outbox_attempt),'terminalFailed',(SELECT count(*) FROM indexnow_outbox WHERE status IN ('permanent_failed','dead_letter') AND id IN (SELECT outbox_id FROM indexnow_outbox_attempt)),'newPublishedArticles',(SELECT count(*) FROM article WHERE published_at>='2026-10-10T06:04:58.665386+00:00'::timestamptz));
 SELECT json_build_object('kind','outbox','id',o.id,'articleId',o.article_id,'url',o.url,'locale',o.locale,'revision',o.revision,'status',o.status,'attemptCount',o.attempt_count,'lastHttpStatus',o.last_http_status,'lastErrorKind',o.last_error_kind,'lastRequestAt',o.last_request_at,'lastResponseAt',o.last_response_at,'payloadHost',o.payload_host,'createdAt',o.created_at,'articleStatus',a.status,'articleLocale',a.locale,'articleType',a.article_type,'seoVisibility',a.seo_visibility,'slug',a.slug,'shortId',a.public_page_short_id,'deliveryTaskId',o.delivery_task_id) FROM indexnow_outbox o LEFT JOIN article a ON a.id=o.article_id ORDER BY o.created_at;
 SELECT json_build_object('kind','attempt','id',id,'outboxId',outbox_id,'attemptNo',attempt_no,'outcome',outcome,'attemptState',attempt_state,'httpStatus',http_status,'errorKind',error_kind,'requestAt',request_at,'responseAt',response_at,'batchSize',batch_size,'workerTaskId',worker_task_id) FROM indexnow_outbox_attempt ORDER BY id;
 SELECT json_build_object('kind','schedule','scheduledFor',scheduled_for,'status',status,'skipReason',skip_reason,'createdAt',created_at) FROM schedule_run WHERE schedule_key='indexnow.sweep' ORDER BY scheduled_for;
 SELECT json_build_object('kind','taskStatus','taskType',task_type,'status',status,'count',count(*)) FROM generic_task WHERE task_type IN ('indexnow_delivery','indexnow.sweep.v1') GROUP BY task_type,status;
 SELECT json_build_object('kind','itemStatus','taskType',t.task_type,'status',i.status,'lockedBy',i.locked_by,'count',count(*)) FROM generic_task_item i JOIN generic_task t ON t.id=i.task_id WHERE t.task_type IN ('indexnow_delivery','indexnow.sweep.v1') GROUP BY t.task_type,i.status,i.locked_by;

COMMIT;
