BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
WITH recent AS (SELECT * FROM indexnow_outbox WHERE created_at > '2026-10-10T17:07:56.462380Z' ORDER BY created_at,id LIMIT 50)
SELECT json_build_object('read_at',clock_timestamp(),'transaction_read_only',current_setting('transaction_read_only'),
'new_outbox_count',(SELECT count(*) FROM indexnow_outbox WHERE created_at > '2026-10-10T17:07:56.462380Z'),
'newly_published_articles',(SELECT json_agg(json_build_object('id',id,'title',title,'locale',locale,'status',status,'published_at',published_at) ORDER BY published_at,id) FROM article WHERE published_at > '2026-10-10T17:07:56.462380Z'),
'new_outbox',(SELECT json_agg(json_build_object('id',o.id,'article_id',o.article_id,'article_title',a.title,'article_status',a.status,'published_at',a.published_at,'outbox_created_at',o.created_at,'outbox_updated_at',o.updated_at,'source',o.source,'event_type',o.event_type,'status',o.status,'attempt_count',o.attempt_count,'last_http_status',o.last_http_status,'last_error_kind',o.last_error_kind,'last_request_at',o.last_request_at,'last_response_at',o.last_response_at,'publish_to_response_seconds',extract(epoch FROM o.last_response_at-a.published_at),'created_to_response_seconds',extract(epoch FROM o.last_response_at-o.created_at)) ORDER BY o.created_at,o.id) FROM recent o LEFT JOIN article a ON a.id=o.article_id),
'new_attempts',(SELECT json_agg(json_build_object('id',x.id,'outbox_id',x.outbox_id,'attempt_no',x.attempt_no,'outcome',x.outcome,'attempt_state',x.attempt_state,'request_batch_id',x.request_batch_id,'batch_size',x.batch_size,'http_status',x.http_status,'error_kind',x.error_kind,'request_at',x.request_at,'response_at',x.response_at,'worker_task_id',x.worker_task_id) ORDER BY x.id) FROM indexnow_outbox_attempt x JOIN recent o ON o.id=x.outbox_id),
'delivery_task_items',(SELECT json_agg(json_build_object('task_id',t.id,'task_type',t.task_type,'task_status',t.status,'total_count',t.total_count,'item_id',i.id,'target_type',i.target_type,'target_id',i.target_id,'item_status',i.status,'payload_mode',i.payload->>'mode','payload_has_outbox_id',i.payload ? 'outboxId','result_mode',i.result->>'mode','result_request_batch_id',i.result->>'requestBatchId','result_claimed',i.result->>'claimed','result_http_status',i.result->>'httpStatus','result_outcome',i.result->>'outcome','result_reason',i.result->>'reason','started_at',i.started_at,'finished_at',i.finished_at) ORDER BY t.created_at,i.id) FROM generic_task t JOIN generic_task_item i ON i.task_id=t.id WHERE t.id IN (SELECT DISTINCT x.worker_task_id FROM indexnow_outbox_attempt x JOIN recent o ON o.id=x.outbox_id)),
'outbox_urls_by_status',(SELECT json_object_agg(status,n) FROM (SELECT status,count(*) n FROM indexnow_outbox GROUP BY status) x),
'sweep_schedule_latest',(SELECT json_agg(json_build_object('scheduled_for',scheduled_for,'status',status) ORDER BY scheduled_for) FROM (SELECT scheduled_for,status FROM schedule_run WHERE schedule_key='indexnow.sweep' ORDER BY scheduled_for DESC LIMIT 10) x));
COMMIT;
