auth_basic "CPS Novel Preproduction";
auth_basic_user_file /opt/cps-novel/shared/secrets/nginx-preprod.htpasswd;
if (-f /opt/cps-novel/shared/maintenance/enabled) { return 503; }
include /etc/nginx/snippets/cps-novel-preprod-security.conf;
