BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL statement_timeout='30s';
SELECT json_build_object('section','identity','role',current_user,'readAt',clock_timestamp(),'readOnly',current_setting('transaction_read_only'));
SELECT json_build_object('section','task','id',id,'taskType',task_type,'channelAppId',channel_app_id,'channelAccountId',channel_account_id,'mode',mode,'status',status,'totalCount',total_count,'successCount',success_count,'failedCount',failed_count,'skippedCount',skipped_count,'requestedAt',requested_at,'startedAt',started_at,'completedAt',completed_at) FROM channel_sync_task WHERE id='943f0f7f-1196-4792-b28f-2ea53bcdf7d1';
SELECT json_build_object('section','itemStatusCounts','counts',json_agg(row_to_json(q))) FROM (SELECT status,count(*) AS count FROM channel_sync_task_item WHERE task_id='943f0f7f-1196-4792-b28f-2ea53bcdf7d1' GROUP BY status ORDER BY status) q;
WITH ranked AS (SELECT novel_source_item_id AS "sourceItemId",error#>>'{detail,kind}' AS kind,error#>>'{detail,stage}' AS stage,error#>>'{detail,receivedType}' AS "receivedType",error#>'{detail,chapterIndex}' AS "chapterIndex",error#>'{detail,chapterOrdinal}' AS "chapterOrdinal",row_number() OVER (PARTITION BY error#>>'{detail,kind}',error#>>'{detail,stage}' ORDER BY novel_source_item_id) AS rn FROM channel_sync_task_item WHERE task_id='943f0f7f-1196-4792-b28f-2ea53bcdf7d1' AND status='failed')
SELECT json_build_object('section','failureGroups','groups',json_agg(row_to_json(q))) FROM (SELECT kind,stage,count(*) AS count,json_agg(json_build_object('sourceItemId',"sourceItemId",'receivedType',"receivedType",'chapterIndex',"chapterIndex",'chapterOrdinal',"chapterOrdinal") ORDER BY "sourceItemId") FILTER (WHERE rn<=2) AS representatives FROM ranked GROUP BY kind,stage ORDER BY kind,stage) q;
SELECT json_build_object('section','detailKeys','keys',json_agg(row_to_json(q))) FROM (SELECT k.key,count(*) AS count FROM channel_sync_task_item i CROSS JOIN LATERAL jsonb_object_keys(i.error->'detail') k(key) WHERE i.task_id='943f0f7f-1196-4792-b28f-2ea53bcdf7d1' AND i.status='failed' GROUP BY k.key ORDER BY k.key) q;
SELECT json_build_object('section','items','items',json_agg(row_to_json(q) ORDER BY q."sourceItemId")) FROM (SELECT i.id AS "itemId",i.novel_source_item_id AS "sourceItemId",s.novel_id AS "novelId",n.title,i.status,i.attempt_count AS "attemptCount",i.error->>'code' AS "errorCode",jsonb_strip_nulls(jsonb_build_object('kind',i.error#>'{detail,kind}','stage',i.error#>'{detail,stage}','errorClass',i.error#>'{detail,errorClass}','adapterCode',i.error#>'{detail,adapterCode}','receivedType',i.error#>'{detail,receivedType}','chapterIndex',i.error#>'{detail,chapterIndex}','chapterOrdinal',i.error#>'{detail,chapterOrdinal}','chapterCount',i.error#>'{detail,chapterCount}')) AS detail,i.started_at AS "startedAt",i.finished_at AS "finishedAt",(SELECT count(*) FROM novel_chapter_content cc WHERE cc.source_fetch_id=i.id) AS "writtenChapterCount",(SELECT count(*) FROM novel_chapter c JOIN novel_chapter_content cc ON cc.novel_chapter_id=c.id WHERE c.novel_id=n.id AND c.status='preview' AND c.deleted_at IS NULL AND btrim(cc.body)<>'') AS "readablePreviewChapterCount" FROM channel_sync_task_item i JOIN novel_source_item s ON s.id=i.novel_source_item_id JOIN novel n ON n.id=s.novel_id WHERE i.task_id='943f0f7f-1196-4792-b28f-2ea53bcdf7d1') q;
SELECT json_build_object('section','oldComparison','counts',json_agg(row_to_json(q))) FROM (SELECT i.status,i.error->>'code' AS code,count(*) AS count FROM channel_sync_task_item i WHERE i.task_id='36e3a15b-61f3-4960-8bcf-c585f648db1f' GROUP BY i.status,i.error->>'code') q;
SELECT json_build_object('section','postActiveHolds','holds',coalesce(json_agg(json_build_object('id',id,'scope',scope,'reasonCode',reason_code)),'[]'::json)) FROM channel_account_hold WHERE channel_account_id='53f03fd8-951d-433e-ac66-784e82496a84' AND scope='preview' AND released_at IS NULL;
COMMIT;
