/**
 * Public Article URL path builder (v0.2.0 foundation, Stream F). Ported from
 * CPS `src/lib/drama-article-path.ts` (55 lines).
 *
 * One structural simplification versus the CPS original, per this round's
 * task book: CPS's `shortId` was optional and gated behind a `flagOn`
 * rollout flag (drama pages could render without a short id during
 * migration). cps-novel's `Article.publicPageShortId` is a required, unique,
 * non-null column from day one (`prisma/schema.prisma` — `Article` model) —
 * there is no legacy population to roll out against, so the
 * `flagOn`/optional-shortId branch is deleted entirely rather than ported;
 * every Article path always includes its short id suffix.
 *
 * Route segment is `/novel/` (matching `src/app/dev-preview/novel/`), not
 * CPS's `/drama/`.
 *
 * C-29 (`规划_文章管理能力补齐_博客类型可见性换小说_2026-09-08.md` §三/C-29)
 * adds a second, parallel path family below: `buildBlogPath`/
 * `buildBlogRoutePath`, route segment `/blog/`. Deliberately no short id
 * suffix on the blog family — "注意博客路径不带短码" per the plan, matching
 * CPS's own blog routing (the short id there is a `novel_article`-only
 * concept; a blog Article's route primary key is its slug alone, and this
 * codebase's `Article.slug` is already unique per `(locale)` among
 * non-deleted rows regardless of type — see
 * `docs/governance/database-governance.md` §5 item 5).
 *
 * 🔴 Sole URL-construction entry point for public Article pages (both
 * families) — sitemap, IndexNow, CTA links, admin preview links, and
 * structured data must all call these functions rather than concatenating
 * paths inline (see `src/lib/slug/README.md`).
 */
import type { SiteLocale } from "@/lib/locale/locale-canonical";

export type ArticlePathInput = {
  readonly locale: SiteLocale;
  readonly slug: string;
  readonly shortId: string;
};

export type ArticleRoutePathInput = {
  readonly slug: string;
  readonly shortId: string;
};

function localePrefix(locale: SiteLocale): string {
  return locale === "en" ? "" : `/${locale}`;
}

export function buildArticleUrlSuffix(shortId: string): string {
  return `p${shortId}`;
}

function buildArticleRouteSlug(input: ArticleRoutePathInput): string {
  return `${input.slug}-${buildArticleUrlSuffix(input.shortId)}`;
}

/** Locale-independent path segment, e.g. `/novel/my-title-p1a2b3c4`. */
export function buildArticleRoutePath(input: ArticleRoutePathInput): string {
  return `/novel/${encodeURIComponent(buildArticleRouteSlug(input))}`;
}

/** Full site-relative path including the locale prefix (empty for `en`). */
export function buildArticlePath(input: ArticlePathInput): string {
  return `${localePrefix(input.locale)}${buildArticleRoutePath(input)}`;
}

export type ParsedArticleSlugParam = {
  readonly slugPart: string;
  readonly shortId: string;
};

/**
 * Inverse of `buildArticleRouteSlug`: splits a route param like
 * `my-title-p1a2b3c4` back into its slug and short-id parts. Matches the
 * short id's actual physical shape (`Article.publicPageShortId
 * @db.VarChar(32)`, lowercase alphanumeric, generated by `src/lib/slug/`'s
 * short-id generator) rather than CPS's fixed 8-character assumption —
 * cps-novel has not frozen a fixed length for this field.
 */
export function parseArticleSlugParam(param: string): ParsedArticleSlugParam | null {
  const match = param.match(/-p([a-z0-9]+)$/);
  if (!match || match.index === undefined) return null;

  return {
    slugPart: param.slice(0, match.index),
    shortId: match[1]!,
  };
}

// ---------------------------------------------------------------------------
// C-29 blog family. No short id, no route-param parsing needed — the `[slug]`
// dynamic segment IS the Article's `slug` column directly (Next.js already
// URL-decodes route params for us on the read side).
// ---------------------------------------------------------------------------

export type BlogRoutePathInput = {
  readonly slug: string;
};

export type BlogPathInput = {
  readonly locale: SiteLocale;
  readonly slug: string;
};

/** Locale-independent path segment, e.g. `/blog/my-post-title`. */
export function buildBlogRoutePath(input: BlogRoutePathInput): string {
  return `/blog/${encodeURIComponent(input.slug)}`;
}

/** Full site-relative path including the locale prefix (empty for `en`). */
export function buildBlogPath(input: BlogPathInput): string {
  return `${localePrefix(input.locale)}${buildBlogRoutePath(input)}`;
}
