/**
 * Public Article URL path builder (v0.2.0 foundation, Stream F). Ported from
 * CPS `src/lib/drama-article-path.ts` (55 lines).
 *
 * One structural simplification versus the CPS original, per this round's
 * task book: CPS's `shortId` was optional and gated behind a `flagOn`
 * rollout flag (drama pages could render without a short id during
 * migration). cps-novel's `Article.publicPageShortId` is a required, unique,
 * non-null column from day one (`prisma/schema.prisma` — `Article` model) —
 * there is no legacy population to roll out against, so the
 * `flagOn`/optional-shortId branch is deleted entirely rather than ported;
 * every Article path always includes its short id suffix.
 *
 * Route segment is `/novel/` (matching `src/app/dev-preview/novel/`), not
 * CPS's `/drama/`.
 *
 * 🔴 Sole URL-construction entry point for public Article pages — sitemap,
 * IndexNow, CTA links, admin preview links, and structured data must all
 * call these functions rather than concatenating paths inline (see
 * `src/lib/slug/README.md`).
 */
import type { SiteLocale } from "@/lib/locale/locale-canonical";

export type ArticlePathInput = {
  readonly locale: SiteLocale;
  readonly slug: string;
  readonly shortId: string;
};

export type ArticleRoutePathInput = {
  readonly slug: string;
  readonly shortId: string;
};

function localePrefix(locale: SiteLocale): string {
  return locale === "en" ? "" : `/${locale}`;
}

export function buildArticleUrlSuffix(shortId: string): string {
  return `p${shortId}`;
}

function buildArticleRouteSlug(input: ArticleRoutePathInput): string {
  return `${input.slug}-${buildArticleUrlSuffix(input.shortId)}`;
}

/** Locale-independent path segment, e.g. `/novel/my-title-p1a2b3c4`. */
export function buildArticleRoutePath(input: ArticleRoutePathInput): string {
  return `/novel/${encodeURIComponent(buildArticleRouteSlug(input))}`;
}

/** Full site-relative path including the locale prefix (empty for `en`). */
export function buildArticlePath(input: ArticlePathInput): string {
  return `${localePrefix(input.locale)}${buildArticleRoutePath(input)}`;
}

export type ParsedArticleSlugParam = {
  readonly slugPart: string;
  readonly shortId: string;
};

/**
 * Inverse of `buildArticleRouteSlug`: splits a route param like
 * `my-title-p1a2b3c4` back into its slug and short-id parts. Matches the
 * short id's actual physical shape (`Article.publicPageShortId
 * @db.VarChar(32)`, lowercase alphanumeric, generated by `src/lib/slug/`'s
 * short-id generator) rather than CPS's fixed 8-character assumption —
 * cps-novel has not frozen a fixed length for this field.
 */
export function parseArticleSlugParam(param: string): ParsedArticleSlugParam | null {
  const match = param.match(/-p([a-z0-9]+)$/);
  if (!match || match.index === undefined) return null;

  return {
    slugPart: param.slice(0, match.index),
    shortId: match[1]!,
  };
}
