/**
 * Public Article URL path builder (v0.2.0 foundation, Stream F). Ported from
 * CPS `src/lib/drama-article-path.ts` (55 lines).
 *
 * One structural simplification versus the CPS original, per this round's
 * task book: CPS's `shortId` was optional and gated behind a `flagOn`
 * rollout flag (drama pages could render without a short id during
 * migration). cps-novel's `Article.publicPageShortId` is a required, unique,
 * non-null column from day one (`prisma/schema.prisma` — `Article` model) —
 * there is no legacy population to roll out against, so the
 * `flagOn`/optional-shortId branch is deleted entirely rather than ported;
 * every Article path always includes its short id suffix.
 *
 * Route segment is `/novel/` (matching `src/app/dev-preview/novel/`), not
 * CPS's `/drama/`.
 *
 * C-29 (`规划_文章管理能力补齐_博客类型可见性换小说_2026-09-08.md` §三/C-29)
 * adds a second, parallel path family below: `buildBlogPath`/
 * `buildBlogRoutePath`, route segment `/blog/`. Deliberately no short id
 * suffix on the blog family — "注意博客路径不带短码" per the plan, matching
 * CPS's own blog routing (the short id there is a `novel_article`-only
 * concept; a blog Article's route primary key is its slug alone, and this
 * codebase's `Article.slug` is already unique per `(locale)` among
 * non-deleted rows regardless of type — see
 * `docs/governance/database-governance.md` §5 item 5).
 *
 * 🔴 Sole URL-construction entry point for public Article pages (both
 * families) — sitemap, IndexNow, CTA links, admin preview links, and
 * structured data must all call these functions rather than concatenating
 * paths inline (see `src/lib/slug/README.md`).
 */
import type { SiteLocale } from "@/lib/locale/locale-canonical";

export type ArticlePathInput = {
  readonly locale: SiteLocale;
  readonly slug: string;
  readonly shortId: string;
};

export type ArticleRoutePathInput = {
  readonly slug: string;
  readonly shortId: string;
};

/**
 * As-needed locale URL prefix: empty for the default locale (`en`), `/{locale}`
 * for every other registered locale.
 *
 * 🔴 Sole prefix-building implementation (D-8). WO-2
 * (`施工工单_WO1-3_多语种公开站地基_2026-09-08.md` §8.1) exports it for reuse
 * by every other in-site link that must react to the currently-served
 * locale — `chromeFromSiteSetting`'s nav/brand hrefs, the category taxonomy
 * projection, the `_pages/*` basePath/homeHref props, and the locale
 * switcher — rather than writing a second copy of this rule.
 */
export function localePrefix(locale: SiteLocale): string {
  return locale === "en" ? "" : `/${locale}`;
}

export function buildArticleUrlSuffix(shortId: string): string {
  return `p${shortId}`;
}

function buildArticleRouteSlug(input: ArticleRoutePathInput): string {
  return `${input.slug}-${buildArticleUrlSuffix(input.shortId)}`;
}

/** Locale-independent path segment, e.g. `/novel/my-title-p1a2b3c4`. */
export function buildArticleRoutePath(input: ArticleRoutePathInput): string {
  return `/novel/${encodeURIComponent(buildArticleRouteSlug(input))}`;
}

/** Full site-relative path including the locale prefix (empty for `en`). */
export function buildArticlePath(input: ArticlePathInput): string {
  return `${localePrefix(input.locale)}${buildArticleRoutePath(input)}`;
}

export type ParsedArticleSlugParam = {
  readonly slugPart: string;
  readonly shortId: string;
};

/**
 * Inverse of `buildArticleRouteSlug`: splits a route param like
 * `my-title-p1a2b3c4` back into its slug and short-id parts. Matches the
 * short id's actual physical shape (`Article.publicPageShortId
 * @db.VarChar(32)`, lowercase alphanumeric, generated by `src/lib/slug/`'s
 * short-id generator) rather than CPS's fixed 8-character assumption —
 * cps-novel has not frozen a fixed length for this field.
 */
export function parseArticleSlugParam(param: string): ParsedArticleSlugParam | null {
  const match = param.match(/-p([a-z0-9]+)$/);
  if (!match || match.index === undefined) return null;

  return {
    slugPart: param.slice(0, match.index),
    shortId: match[1]!,
  };
}

/**
 * Safe decode for a raw `[slugParam]`/`[slug]` dynamic-route segment, called
 * once at each page-body entry point right after destructuring `params` —
 * CPS parity: `normalizeRouteSlug`,
 * `git show 3a76877:src/app/[locale]/(site)/drama/[slug]/page.tsx:84-89`
 * (`try { return decodeURIComponent(slug); } catch { return slug; }`,
 * called independently from both `generateMetadata` and the page body).
 * `parseArticleSlugParam`/CPS's `parseDramaArticleSlugParam` both
 * deliberately do NOT decode internally — `src/server/articles/service.ts`'s
 * `extractSearchShortId` already decodes an admin-pasted URL *before*
 * calling `parseArticleSlugParam`, so decoding a second time inside it would
 * double-decode that caller. This is the sibling boundary for the public
 * route's own raw `params.slugParam`.
 *
 * Not a parity gap versus CPS's own `normalizeRouteSlug`: Next.js does not
 * URL-decode a dynamic route segment for a `force-dynamic` (non-SSG) App
 * Router page — confirmed empirically against the pinned `next@16.1.6`
 * (`output: "standalone"`) build, not merely inferred from the framework's
 * `getStaticPaths`-era decode path
 * (`node_modules/next/dist/server/lib/router-utils/decode-path-params.js`'s
 * own header comment: "We only encode path delimiters for path segments
 * from getStaticPaths... TODO: investigate adding this handling for
 * non-SSG pages so non-ascii names also work there"). A percent-encoded
 * non-ASCII slug therefore reaches `params.slugParam` still encoded; every
 * public Article/chapter page must decode it itself before resolving.
 */
export function decodeSlugParam(raw: string): string {
  try {
    return decodeURIComponent(raw);
  } catch {
    return raw;
  }
}

// ---------------------------------------------------------------------------
// C-29 blog family. No short id, no route-param parsing needed — the `[slug]`
// dynamic segment IS the Article's `slug` column directly (Next.js already
// URL-decodes route params for us on the read side).
// ---------------------------------------------------------------------------

export type BlogRoutePathInput = {
  readonly slug: string;
};

export type BlogPathInput = {
  readonly locale: SiteLocale;
  readonly slug: string;
};

/** Locale-independent path segment, e.g. `/blog/my-post-title`. */
export function buildBlogRoutePath(input: BlogRoutePathInput): string {
  return `/blog/${encodeURIComponent(input.slug)}`;
}

/** Full site-relative path including the locale prefix (empty for `en`). */
export function buildBlogPath(input: BlogPathInput): string {
  return `${localePrefix(input.locale)}${buildBlogRoutePath(input)}`;
}
